CREATE TABLE documento (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_documento VARCHAR(100),
    folio VARCHAR(100),
    folio_documento VARCHAR(100),
    numero_expediente VARCHAR(100),
    nombre_expediente VARCHAR(100),
    fecha_documento DATETIME,
    asunto VARCHAR(100),
    contenido VARCHAR(100),
    nota VARCHAR(100),
    documento LONGBLOB,
    porcentaje_firma FLOAT,
    cargo VARCHAR(100),
    id_tipouso INT,
    id_areadestino INT,
    id_areacopia INT,
    id_tipodocumento INT,
    id_destinatario INT,
    id_elaboro INT,
    id_estadodocumento INT,
    activo BOOLEAN,
    fh_creacion DATETIME,
    fh_modificacion DATETIME,
    usu_creacion INT,
    usu_modificacion INT,
    CONSTRAINT fk_doc_id_tipouso FOREIGN KEY (id_tipouso) REFERENCES cat_tipouso(id),
    CONSTRAINT fk_doc_id_areadestino FOREIGN KEY (id_areadestino) REFERENCES cat_area(id),
    CONSTRAINT fk_doc_id_areacopia FOREIGN KEY (id_areacopia) REFERENCES cat_area(id),
    CONSTRAINT fk_doc_id_tipodocumento FOREIGN KEY (id_tipodocumento) REFERENCES cat_tipodocumento(id),
    CONSTRAINT fk_doc_id_elaboro FOREIGN KEY (id_elaboro) REFERENCES usuario(id),
    CONSTRAINT fk_doc_id_destinatario FOREIGN KEY (id_destinatario) REFERENCES usuario(id),
    CONSTRAINT fk_doc_id_estadodocumento FOREIGN KEY (id_estadodocumento) REFERENCES cat_estado(id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE asignacion (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_documento INT,
    id_usuario INT,
    id_accion INT,
    id_estadoaccion INT,
    id_tipoasociacion INT,
    obligatorio BOOLEAN,
    activo BOOLEAN,
    fh_creacion DATETIME,
    fh_modificacion DATETIME,
    usu_creacion INT,
    usu_modificacion INT,
    CONSTRAINT fk_asi_id_documento FOREIGN KEY (id_documento) REFERENCES documento(id),
    CONSTRAINT fk_asi_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id),
    CONSTRAINT fk_asi_id_accion FOREIGN KEY (id_accion) REFERENCES cat_accion(id),
    CONSTRAINT fk_asi_id_tipoasociacion FOREIGN KEY (id_tipoasociacion) REFERENCES cat_tipoasociacion(id),
    CONSTRAINT fk_asi_id_estadoaccion FOREIGN KEY (id_estadoaccion) REFERENCES cat_estado(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
